### ISSUE TITLE
eos_l3_interfaces does not set `no switchport` for routed ports

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#101]
Consider the following playbook:

```yaml
- name: Replace device configuration of specified L2 interfaces with provided configuration.
  arista.eos.eos_l3_interfaces:
    config:
    - name: Ethernet5
      ipv4:
      - address: 192.168.100.5/24
    state: overridden
```

That renders the following config in EOS

```
interface Ethernet5
   ip address 192.168.100.5/24
!
```

The issue is that without a `no switchport` stanza for the interface defintion, EOS reports 
`! IP configuration will be ignored while interface Ethernet5 is not a routed port.` when you enter this IP address by hand.

Which when you do an `ip route` commmand, you will see that a routing table entry is not set for the connected device

```
localhost(config)#show ip route

VRF name: default
Codes: C - connected, S - static, K - kernel,
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
       R - RIP, I L1 - ISIS level 1, I L2 - ISIS level 2,
       A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route, V - VXLAN Control Service

Gateway of last resort is not set

 C      10.0.2.0/24 is directly connected, Management1
```

Now, back when using `eos_l3_interface` - I would prep an interface for being a routed port by doing `eos_l2_interface` as follows:

```yaml

tasks:
    - name: Ensure that no switchport is set on the port
      eos_l2_interface:
        name: Ethernet5
        state: absent


    - name: use eos l3 interface old module
      eos_l3_interface:
        name: Ethernet5
        ipv4: 192.168.100.5/24

```

Which would render the following:

```
interface Ethernet5
   no switchport
   ip address 192.168.100.5/24
!
```

Which would then have everything work properly

```
localhost(config-if-Et5)#show ip route

VRF name: default
Codes: C - connected, S - static, K - kernel,
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
       R - RIP, I L1 - ISIS level 1, I L2 - ISIS level 2,
       A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route, V - VXLAN Control Service

Gateway of last resort is not set

 C      10.0.2.0/24 is directly connected, Management1
 C      192.168.100.0/24 is directly connected, Ethernet5
```
