### ISSUE TITLE
eos_l2_interfaces not adding switchport mode trunk

### ISSUE THREAD

**Issue by jshively37** [ansible-collections/arista.eos#112]
##### SUMMARY
When using eos_l2_interfaces module with trunk keyword the command switchport mode trunk is not entered. I am also seeing when I hardcode the port to switchport mode trunk from the CLI and use the access keyword in the module that switchport mode trunk is not removed and switchport mode access is not applied.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_l2_interfaces module (I have also tried the collections with the same result).

##### ANSIBLE VERSION

```
ansible 2.9.13 (I have tested with 2.9.10 and the same result).
  config file = /Users/shivelyj/git_repo/ansible_projects/customer/customer_arista/ansible.cfg
  configured module search path = ['/Users/shivelyj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/shivelyj/.local/share/virtualenvs/customer/lib/python3.8/site-packages/ansible
  executable location = /Users/shivelyj/.local/share/virtualenvs/customer/bin/ansible
  python version = 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) [Clang 6.0 (clang-600.0.57)]

```

##### CONFIGURATION

```
HOST_KEY_CHECKING(/Users/shivelyj/git_repo/ansible_projects/customer/customer_arista/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/shivelyj/git_repo/ansible_projects/customer/customer_arista/ansible.cfg) = /Users/shivelyj/.local/share/virtualenvs/customer-fTYycXwc/bin/python

```

##### OS / ENVIRONMENT

MAC 10.15.6

##### STEPS TO REPRODUCE

```yaml
role/tasks/main.yml
- name: Configure L2 Interface Information
  eos_l2_interfaces:
    config: "{{ config }}"
    state: "{{ state | d('replaced') }}"

host_vars/switch.yml:
l2_interfaces:
  - name: Ethernet1
    trunk:
      trunk_allowed_vlans: 10,11
      native_vlan: 999
  - name: Ethernet2
    trunk:
      trunk_allowed_vlans: 20,21
      native_vlan: 999
  - name: Ethernet3
    access:
      vlan: 20

main_playbook:
        - name: Configure L2 Interfaces
          include_role:
            name: arista-eos-l2-interfaces
          vars:
            config: "{{ l2_interfaces }}"
            state: "{{ interfaces_state | d(omit) }}"
          when: l2_interfaces is defined

This is also using the network_cli

```

##### EXPECTED RESULTS

interface Ethernet1
   switchport mode trunk
   switchport trunk native vlan 999
   switchport trunk allowed vlan 10-11

##### ACTUAL RESULTS

The interface is still configured as the default port state of access
interface Ethernet1
   switchport trunk native vlan 999
   switchport trunk allowed vlan 10-11

```paste below

```

**Comment by jshively37** [comment]
Looking through the code it appears you have to send mode with it (we did not see mode listed on the readme though as a valid option).

If I do:
```
  - name: Ethernet1
    mode: trunk
    trunk:
      trunk_allowed_vlans: 10,11
      native_vlan: 999
  - name: Ethernet3
    mode: access
    access:
      vlan: 20
```
It works as expected.

Output from switch:
```
interface Ethernet1
   description test_server_data
   switchport trunk native vlan 999
   switchport trunk allowed vlan 10-11
   switchport mode trunk
interface Ethernet3
   description testing
   switchport access vlan 20
```
The ethernet3 I do not expect switchport mode access to appear in the configuration since this is default behavior.
