### ISSUE TITLE
eos_acls : protocol flag not set correctly

### ISSUE THREAD

**Issue by GomathiselviS** [ansible-collections/arista.eos#114]
##### SUMMARY

When 'flags' is passed with protocol_options for protocol = "tcp", the option is not configured properly.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_acls
##### ANSIBLE VERSION

```
ansible 2.11.0.dev0


```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
Use playbook:


- name: Merge provided configuration with device configuration
    arista.eos.eos_acls:
      config:
        - afi: "ipv4"
          acls:
           - name: acl01
             aces:
               - sequence: 35
                 grant: "deny"
                 protocol: "ospf"
                 source:
                   subnet_address: 20.0.0.0/8
                 destination:
                   any: true
               - remark: "Run by ansible"
               - grant: "permit"
                 protocol: "6"
                 protocol_options:
                  tcp:
                    flags:
                      syn: True
                 source:
                  any: true
                 destination:
                  any: true
      state: merged


```

##### EXPECTED RESULTS

configuration pushed successfully
##### ACTUAL RESULTS

```

task errors

```
