### ISSUE TITLE
Not possible to set "speed forced 40gfull" using eos_interfaces

### ISSUE THREAD

**Issue by agunnerson-ibm** [ansible-collections/arista.eos#117]
##### SUMMARY

The following task fails when setting the speed of a port because `eos_interfaces` is not aware of the `forced` option (eg. `speed forced 40gfull`).

```yaml
- name: Set interface speed
  eos_interfaces:
    config:
      name: Ethernet49/1
      speed: 40g
      duplex: full
```

Using:

```yaml
- name: Set interface speed
  eos_interfaces:
    config:
      name: Ethernet49/1
      speed: forced 40g
      duplex: full
```

works the first time, but will fail with a `KeyError` for `duplex` in `generate_commands` due to `_state_merged` seeing `40g` (extant) vs `forced 40g` (desired), while `duplex` is not changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`eos_interfaces` module

##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /Users/andrew.gunnerson/git/<redacted>/ansible.cfg
  configured module search path = ['/Users/andrew.gunnerson/git/<redacted>/library']
  ansible python module location = /Users/andrew.gunnerson/git/<redacted>/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/andrew.gunnerson/git/<redacted>/venv/bin/ansible
  python version = 3.7.3 (default, Apr 24 2020, 18:51:23) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### OS / ENVIRONMENT

```
Arista DCS-7050TX-64-R

Software image version: 4.19.6.3M
Architecture:           i386
Internal build version: 4.19.6.3M-8230431.41963M
Internal build ID:      305c28a7-619e-43cc-84f5-c48f40378301
```
