### ISSUE TITLE
eos_l2_interfaces documentation is unclear about trunk_allowed_vlans list contents

### ISSUE THREAD

**Issue by acalm** [ansible-collections/arista.eos#12]
##### SUMMARY

The documentation for eos_l2_interfaces suggests vlans should be integers, however the list allowed_trunk_vlans is used as a list with strings here: https://github.com/ansible-collections/eos/blob/71b8b03c86d1dc15f2ee3091a9a08080b47a3621/plugins/module_utils/network/eos/config/l2_interfaces/l2_interfaces.py#L241

I understand the underlying switch os doesn't care about types, but it would be nice if the documentation hinted about this or have the join operation not care about what's in the list
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

eos/plugins/modules/eos_l2_interfaces.py 
eos/plugins/module_utils/network/eos/config/l2_interfaces/l2_interfaces.py

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /home/acalm/.ansible.cfg
  configured module search path = ['/home/acalm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/acalm/repos/ansible/lib/ansible
  executable location = /home/acalm/repos/ansible/bin/ansible
  python version = 3.6.10 (default, Feb 27 2020, 10:55:54) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
COLOR_VERBOSE(/home/acalm/.ansible.cfg) = magenta
INVENTORY_IGNORE_EXTS(/home/acalm/.ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.ini', '.cfg', '.retry']
RETRY_FILES_ENABLED(/home/acalm/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
            "ansible_net_python_version": "3.6.10",
            "ansible_net_system": "eos",
            "ansible_net_version": "4.21.6F"
```
##### STEPS TO REPRODUCE

```yaml
---
- name: configure switch ports
   become: true
   eos_l2_interfaces:
     config:
       - name: Ethernet1
         trunk:
           native_vlan: 78
           trunk_allowed_vlans:
           - 10
           - 790
     state: merged
```

##### EXPECTED RESULTS

A successful run
##### ACTUAL RESULTS

```paste below
...
  File "/tmp/ansible_eos_l2_interfaces_payload_6_87aisf/ansible_eos_l2_interfaces_payload.zip/ansible/module_utils/network/eos/config/l2_interfaces/l2_interfaces.py", line 225, in set_interface
TypeError: sequence item 0: expected str instance, int found
```
