### ISSUE TITLE
Add support for syntax changes in release train 4.23 and after

### ISSUE THREAD

**Issue by ctilley1407** [ansible-collections/arista.eos#133]
##### SUMMARY

As of roughly August 2019, Arista released train 4.23.X and newer and along with it replaced and deprecated lots of commands:
https://www.arista.com/en/support/advisories-notices/fieldnotices/7097-field-notice-39

It would be good to have the newer syntax supported alongside the deprecated commands.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

arista.eos_*

##### ADDITIONAL INFORMATION

This feature would be used to support the syntax changes in newer software releases of EOS.
This is needed because certain configuration commands no longer exists and therefore errors are encountered.

For example:
When running tasks with a VRF set, they fail with an error suggesting the VRF is not configured:

```bash
fatal: [eos-test]: FAILED! => {"changed": false, "msg": "vrf mgmt is not configured"}
```

This is because the module is looking for "vrf definition" rather than "vrf instance" in the config.

```yaml
---
- name: Base system profile
   hosts: all
   collections:
     - arista.eos
   vars:
      ansible_connection: network_cli
      ansible_network_os: eos
      eos_name_servers:
        - server: 1.1.1.1
          vrf: mgmt
   tasks:
     - name: Set name servers
       eos_system:
       name_servers: "{{ eos_name_servers }}"
```

An example of where this needs updating is in the eos_system module:
```python
def has_vrf(module, vrf):
    global _CONFIGURED_VRFS
    if _CONFIGURED_VRFS is not None:
        return vrf in _CONFIGURED_VRFS
    config = get_config(module)
    _CONFIGURED_VRFS = re.findall(r"vrf definition (\S+)", config)
    _CONFIGURED_VRFS.append("default")
    return vrf in _CONFIGURED_VRFS
```
