### ISSUE TITLE
ip address virtual shows up as a 0.0.0.0/0 IP in eos_facts

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#148]
##### SUMMARY
`show ip interface brief` command properly shows the applied ip address virtual command for an interface configured as such, but eos_facts does.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_facts

##### ANSIBLE VERSION

```paste below
2.10.5
```

##### CONFIGURATION

```paste below
<empty>
```

##### OS / ENVIRONMENT

Arista EOS 4.22.6M, 4.23.5M, & 4.24.3M

interface config:
```
interface Vlan100
   description test
   ip address virtual 10.0.0.1/16
```

##### STEPS TO REPRODUCE

```yaml
- name: eos_facts
  arista.eos.eos_facts:
    gather_subset: all
    gather_network_resources: all
```

##### EXPECTED RESULTS

```
<omitted output before this>
ansible_net_interfaces:
  Vlan100:
    bandwidth: 0
    description: test
    ipv4:
      address: 10.0.0.1
      masklen: 16
    lineprotocol up
    macaddress: aa:aa:aa:aa:aa:aa
    mtu: 1500
    operstatus: up
    type: routed
```

##### ACTUAL RESULTS

```
<omitted output before this>
ansible_net_interfaces:
  Vlan100:
    bandwidth: 0
    description: test
    ipv4:
      address: 0.0.0.0
      masklen: 0
    lineprotocol up
    macaddress: aa:aa:aa:aa:aa:aa
    mtu: 1500
    operstatus: up
    type: routed
```
