### ISSUE TITLE
Capture Secondary IP in eos_facts

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#149]
##### SUMMARY

capture the associated `ip address <address> secondary` IPs associated to an interface.  You could add a new list to the ansible_net_interfaces called `secondary_ips`

```
<omitted output before this>
ansible_net_interfaces:
  Vlan100:
    bandwidth: 0
    description: test
    ipv4:
      address: 10.0.0.1
      masklen: 16
    secondary_ips:
        - address: 1.1.1.1
          masklen: 24
    lineprotocol up
    macaddress: aa:aa:aa:aa:aa:aa
    mtu: 1500
    operstatus: up
    type: routed
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

eos_facts

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by GomathiselviS** [comment]
@ryanmerolle : Thank you for submitting the issue. `secondary ip` value is available in the l3_interfaces facts. `ansible_net_interfaces` is a legacy implementation . Hence we will not be adding any new feature / key to it. To get the l3_interfaces facts, you can use the following playbook .

```
tasks:
  - name: Facts
    arista.eos.eos_facts:
      gather_subset:
        - min
      gather_network_resources: l3_interfaces
```
The output will be

```
 "ansible_network_resources": {
        "l3_interfaces": [
            {
                "ipv4": [
                    {
                        "address": "10.1.1.1/24"
                    },
                    {
                        "address": "12.1.1.1/24",
                        "secondary": true
                    }
                ],
                "ipv6": [
                    {
                        "address": "2001:db8:feed::1/96"
                    }
                ],
                "name": "Ethernet1"
            },
  ........
 .....................
      }
  ]
}
```

Please let me know your feedback after using the resource facts.
