### ISSUE TITLE
Add `available_network_resources` key in eos_facts module

### ISSUE THREAD

**Issue by trishnaguha** [ansible-collections/arista.eos#184]
- The key will return the list of all the RM resources available for the platform.
- This implementation doesn't affect the current functionality of the eos_facts module and users can use the eos_facts module in the same way as they were before.

Current behavior:
```
---
- name: Fatch facts
  hosts: junos
  gather_facts: no
  collections:
    - arista.eos
  
  tasks:
    - name: Get basic facts 
      eos_facts:
        gather_subset:
          - '!all'
```
output
```
ok: [10.8.8.31] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_fqdn": "an-veos-01",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "an-veos-01",
        "ansible_net_model": "vEOS",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_serialnum": "",
        "ansible_net_system": "eos",
        "ansible_net_version": "4.15.9M",
        "ansible_network_resources": {},
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
`After implementation of available_network_resources`
`Sample Playbook`:
```
---
- name: Get the list of  available resource Modules
  hosts: eos
  gather_facts: no
  collections:
    - aista.eos
  
  tasks:
    - name: Get the list of available network resources for Arista eos and avoid fetching resource facts
      eos_facts:
        gather_subset:
          - '!all'
        available_network_resources: true
```
Result: 
```
ok: [10.8.8.31] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_fqdn": "an-veos-01",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "an-veos-01",
        "ansible_net_model": "vEOS",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_serialnum": "",
        "ansible_net_system": "eos",
        "ansible_net_version": "4.15.9M",
        "ansible_network_resources": {},
        "available_network_resources": [
            "acl_interfaces",
            "acls",
            "bgp_address_family",
            "bgp_global",
            "interfaces",
            "l2_interfaces",
            "l3_interfaces",
            "lacp",
            "lacp_interfaces",
            "lag_interfaces",
            "lldp_global",
            "lldp_interfaces",
            "ospf_interfaces",
            "ospfv2",
            "ospfv3",
            "static_routes",
            "vlans"
        ],
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": true,
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
