### ISSUE TITLE
eos_command timeout issues

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#220]
##### SUMMARY
When sending a bash command using the commands module & using eAPI, the timeout parameter needs to be set.  When you set the parameter for the timeout AND a register parameter, the module complains/fails because timeout is only enabled for particular parameters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
arista.eos.eos_command

##### ANSIBLE VERSION

```paste below
ansible 2.10.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user1/.local/lib/python3.8/site-packages/ansible
  executable location = /home/user1/.local/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: run multiple commands and evaluate the output
  arista.eos.eos_command:
    timeout: 5
    commands:
      - bash id
      - bash ls
    register: bash_output
```

##### EXPECTED RESULTS

Task runs

##### ACTUAL RESULTS

```paste below
fatal: [test-sw1]: FAILED! => changed=false
  msg: 'Unsupported parameters for (arista.eos.eos_command) module: timeout Supported parameters include: commands, interval, match, provider, retries, wait_for'
```
