### ISSUE TITLE
Route_Maps module does not support all documented options

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#235]
```yaml
    - arista.eos.eos_prefix_lists:
        config: 
          - afi: "ipv4"
            prefix_lists:
              - name: "test_pfx"
                entries:
                  - sequence: 10
                    action: "permit"
                    address: "203.0.113.0/24"
                    match:
                      masklen: 24
                      operator: "ge"

    -  arista.eos.eos_route_maps:
        config: 
          - route_map: "test_map"
            entries:
              - description: "loopback prefix list match"
                action: "permit"
                sequence: 10
                match:
                  ip:
                    address:
                      prefix_list: "test_pfx"

```

Expected configuration
```
!
route-map test_map permit 10
   match ip address prefix-list test_pfx
!
```

Instead it errors out

```
    ansible.module_utils.connection.ConnectionError: match ip
    % Incomplete command
    spine4(config-s-ansibl-route-map-test_map)#
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
