### ISSUE TITLE
Ansible device configuration diff for Arista device needs to provide the context for the diff

### ISSUE THREAD

**Issue by mayanktiwarius** [ansible-collections/arista.eos#248]
##### ISSUE TYPE
The sample code generates and show configuration diff for Arista:
- name: diff the running config against a generated config

  arista.eos.eos_config:

    provider: "{{ arista_eapi_credentials }}"

    diff_against: session

    src: /tmp/{{ inventory_hostname }}_pushconfig.cfg

    replace: config

  check_mode: true

  diff: true

  register: diff_response

Sample output from diff:
@@ -1789,7 +1781,7 @@

    seq 150 permit 162.17.0.0/16 le 30

    seq 160 permit 173.8.0.0/13 le 30

    seq 170 permit 173.160.0.0/13 le 30

-   seq 180 permit 198.0.0.0/16

+   seq 180 permit 198.0.0.0/16 le 30

!

This diff does not show under which section of the configuration this diff is appearing for.

##### ADDITIONAL INFORMATION

```
- name: diff the running config against a generated config

  arista.eos.eos_config:

    provider: "{{ arista_eapi_credentials }}"

    diff_against: session

    src: /tmp/{{ inventory_hostname }}_pushconfig.cfg

    replace: config

  check_mode: true

  diff: true

  register: diff_response
```
