### ISSUE TITLE
bgp_global throws a KeyError when state:replaced and an existing BGP configuration is on the device

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#265]
```yaml
    - name: Configure BGP global options
      arista.eos.bgp_global:
        config:
          as_number: "{{ our_asn }}"
          neighbor: "{{ bgp_neighbors }}"
          redistribute:
            - protocol: connected
              route_map: BGP_OUT
            - protocol: static
              route_map: BGP_OUT
        state: replaced
```

`bgp_neighbors` doesn't have anything special in it. Just a list of BGP neighbors and their IP addresses.

Running the playbook that contains this task the first time succeeds, but subsequent runs fail with the following error:

```
  File "/var/folders/zc/nk7dv4252nx9l_j3p2zshpy1xkp8xq/T/ansible_arista.eos.bgp_global_payload_wser94eq/ansible_arista.eos.bgp_global_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/bgp_global/bgp_global.py", line 347, in _compare_neighbor
KeyError: 'peer'
```

**Comment by GomathiselviS** [comment]
@sc68cal  The neighbor key is a list of dict. -> [neighbor](https://github.com/ansible-collections/arista.eos/blob/main/plugins/modules/eos_bgp_global.py#L322) . The dictionary should have ```peer``` key along with other keys under neighbor. If we provide only the ```peer``` key, it will configure ```neighbor <peer>``` which will be an incomplete command. Can you please try configuring ```neighbor``` in the following format and let me know if you are facing any issues ?

```
arista.eos.eos_bgp_global:
      config:
        as_number: 65535
         neighbor:
              - peer: "12.1.3.2"
                allowas_in:
                  set: true
                default_originate:
                  always: true
                dont_capability_negotiate: true
```
