### ISSUE TITLE
diff_against intended does not output a diff for eos_config

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#285]
##### SUMMARY
When using eos_config module with `diff_against: intended` & the intended_config option, the function does not output a diff.  It only captures a diff.before and a diff.after, but not actual diff.diff or anything close.  Is this a bug or as intended?  I would ask in a discussion section, but that feature is not enabled for this repo.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_config 

##### ANSIBLE VERSION

```paste below
2.10.x & 2.11.x (tested all versions)
```

##### COLLECTION VERSION

```paste below
3.0.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 20.04 / python 3.8

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below
```

**Comment by ryanmerolle** [comment]
I am happy to share more info if this is not how the function is meant to work.

**Comment by GomathiselviS** [comment]
Hi @ryanmerolle  This is not a bug. This is the intended behavior. If you want to register the diff, you can use the ```ansible.utils.fact_diff``` module. A detailed explanation on how to use fact_diff can be found [here](https://www.ansible.com/blog/getting-started-with-route-maps-resource-modules) under ```Using state overridden - Pushing configuration changes``` .  Please try fact_diff and let us know your feedback.

**Comment by ryanmerolle** [comment]
Hello @GomathiselviS, thanks for the help!

That makes perfect sense.  As I thought, this is more of a discussion than an issue.  Apologies for the spam.  Maybe discussions could be enabled.

Besides being able to output the diff with one task any disadvantage or advantage to auditing config using these 2 approaches.

Approach 1:
```
- arista.eos.eos_config
    src: golden_config.cfg
    replace: config
  check_mode: yes
  diff: yes
  register: audit_config
```

Approach 2:
```
- arista.eos.eos_config:
    diff_against: intended
    intended_config: "{{ lookup('file', 'golden_config.cfg') }}"
  check_mode: yes  # Is this even required ?
  register: audit_config

- name: Show the difference
  ansible.utils.fact_diff:
    before: "{{ audit_config.before | ansible.utils.to_paths }}"
    after: "{{ audit_config.after | ansible.utils.to_paths }}"

```
