### ISSUE TITLE
Add management security support in ansible

### ISSUE THREAD

**Issue by lordofire** [ansible-collections/arista.eos#304]
##### SUMMARY
In Arista EOS, we could setup the management security ssl profile with ca, cert, and key. They could be used later to the eapi enable logics and apply the profile into it so that we could use local generated certs to protect the https api endpoint.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
eos_security?

##### ADDITIONAL INFORMATION
```yaml
eos_security:
   ssl_profile:
      name: xxx
      key: xxx
      certificate: xxx
      trust_certificate: xxx
      chain_certificate: xxxx

eos_eapi:
    state: started
    http: false
    https_port: 9443
    profile: xxxx                        <-------------- new field
```
