### ISSUE TITLE
Unsupported parameters for basic.py module

### ISSUE THREAD

**Issue by jhg03a** [ansible-collections/arista.eos#309]
##### SUMMARY

When attempting to use the eos_facts module, I'm receiving an error back similar to #206 reporting unsupported parameters.  I've narrowed it down to only when including acls in the gathered network resources.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

eos_facts

##### ANSIBLE VERSION

```paste below
bash-5.1# ansible --version
ansible [core 2.12.2]
  config file = /app/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /app/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION

```paste below
bash-5.1# ansible-galaxy collection list arista.eos

# /usr/lib/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
arista.eos 3.1.0

# /app/collections/ansible_collections
Collection Version
---------- -------
arista.eos 4.0.0
```

##### CONFIGURATION

```paste below
bash-5.1# ansible-config dump --only-changed
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/app/collections']
DEFAULT_REMOTE_USER(env: ANSIBLE_REMOTE_USER) = jhg03a
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/app/roles']
DEFAULT_TIMEOUT(/app/ansible.cfg) = 30
HOST_KEY_CHECKING(/app/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/app/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/app/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/app/ansible.cfg) = 90
PERSISTENT_CONNECT_TIMEOUT(/app/ansible.cfg) = 90
RETRY_FILES_ENABLED(/app/ansible.cfg) = False
USE_PERSISTENT_CONNECTIONS(/app/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Control host is an alpine 3.15 container
"ansible_net_python_version": "3.9.7",
"ansible_net_system": "eos",
"ansible_net_version": "4.25.4M",
"ansible_net_model": "DCS-7280CR2A-60-F",
"ansible_net_api": "cliconf",

##### STEPS TO REPRODUCE

This reproduce case has an exclusion in order to get past #308.

```yaml
- hosts: target_device
  connection: ansible.netcommon.network_cli
  any_errors_fatal: true
  gather_facts: false
  collections:
    - arista.eos

  tasks:
    - name: Get Facts
      eos_facts:
        gather_subset: all
        available_network_resources: true
        gather_network_resources:
          - '!bgp_address_family'
```

##### EXPECTED RESULTS

Successful execution of the eos_facts module with all values populated

##### ACTUAL RESULTS

```paste below
ansible-playbook [core 2.12.2]
  config file = /app/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /app/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
  jinja version = 3.0.3
  libyaml = False
Using /app/ansible.cfg as config file
host_list declined parsing /app/inventory/anvil.networking.yml as it did not pass its verify_file() method
Parsed /app/inventory/networking.yml inventory source with yaml plugin
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: net.yml ************************************************************************************************************************************************************************************************************************************************************
1 plays in net.yml

PLAY [target_device] ****************************************************************************************************************************************************************************************************************************************************
META: ran handlers
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos

TASK [Get Facts] *************************************************************************************************************************************************************************************************************************************************************
task path: /app/net.yml:14
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
redirecting (type: action) arista.eos.eos_facts to arista.eos.eos
<10.38.137.178> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.38.137.178> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-936v462e285 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531 `" && echo ansible-tmp-1643754312.9916658-941-122010888893531="` echo /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531 `" ) && sleep 0'
Using module file /app/collections/ansible_collections/arista/eos/plugins/modules/eos_facts.py
<10.38.137.178> PUT /root/.ansible/tmp/ansible-local-936v462e285/tmp3x8df9bh TO /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531/AnsiballZ_eos_facts.py
<10.38.137.178> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531/ /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531/AnsiballZ_eos_facts.py && sleep 0'
<10.38.137.178> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531/AnsiballZ_eos_facts.py && sleep 0'
<10.38.137.178> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-936v462e285/ansible-tmp-1643754312.9916658-941-122010888893531/ > /dev/null 2>&1 && sleep 0'
fatal: [target_device]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": null,
                    "afi": "ipv4",
                    "line": "50 permit ip any any dscp af22"
                },
                {
                    "acls": null,
                    "afi": "ipv6",
                    "line": "70 permit ipv6 any any dscp af22"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "Unsupported parameters for (basic.py) module: config.line. Supported parameters include: running_config, state, config."
}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
target_device         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by jhg03a** [comment]
This also appears if you try and use the eos_acls module with state parsed.

**Comment by sc68cal** [comment]
Can also confirm this issue.

```yaml
- hosts: all
  gather_facts: false
  connection: network_cli
  tasks:

    - name: Gather the existing configuration
      arista.eos.eos_acls:
        state: gathered
```

```yaml
fatal: [foo.net]: FAILED! => changed=false
  invocation:
    module_args:
      config:
      - acls: null
        afi: ipv4
        line: 30 permit ip any any
      - acls: null
        afi: ipv6
        line: 30 permit tcp any any eq mlag hop_limit eq 255
      running_config: null
      state: merged
  msg: 'Unsupported parameters for (basic.py) module: config.line. Supported parameters include: config, state, running_config.'
```
