### ISSUE TITLE
The "eos_bgp_global" module does not provide a diff when running "--check --diff"

### ISSUE THREAD

**Issue by richardr1000** [ansible-collections/arista.eos#310]
##### SUMMARY
When using the "eos_bgp_global" module it does not provide a diff when running `--check --diff` and `check_mode` does not seem to do anything with this module. Any suggestions? I had a chat with @GomathiselviS separately and I was asked to make this a formal issue here in github :D

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_bgp_global

##### ANSIBLE VERSION
```
2.10.8
```

##### COLLECTION VERSION
```
$ ansible-galaxy collection list arista.eos

# /Users/me/.ansible/collections/ansible_collections
Collection Version
---------- -------
arista.eos 2.1.1

# /Users/me/.pyenv/versions/3.9.4/lib/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
arista.eos 1.3.0
```

##### CONFIGURATION

```
Hey it's a very simple playbook to test :

---
# file: roles/switch/tasks/test.yml

- name: bgp
  arista.eos.eos_bgp_global:
      config:
         router_id: "{{ hostIP }}"
         as_number: "4200000001"
         bgp_params:
             additional_paths: "send"
             log_neighbor_changes: True
         maximum_paths:
             max_equal_cost_paths: 15
         aggregate_address:
             - address: "{{ switch_IPv6_prefix }}"
      state: merged
  diff: yes
  tags: [ bgp ]


----------------------

and my group_vars has :

ansible_python_interpreter: python
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: arista.eos.eos
ansible_become: yes
ansible_become_method: enable

```

##### OS / ENVIRONMENT
destination device is Arista EOS 4.25.3M

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
