### ISSUE TITLE
Inconsistent use of BGP peer address on eos_bgp_global

### ISSUE THREAD

**Issue by nleiva** [ansible-collections/arista.eos#326]
##### SUMMARY
arista.eos_bgp_global model defines `neighbors.peer` to declare the address of a BGP peer on a Arista EOS device. Both, `nxos_bgp_global` and `ios_bgp_global` use `neighbors.neighbor_address` for the same purpose (and soon IOS XR as well). I don't have a preference, I would just prefer a consistent field name for them all. Thanks.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

arista.eos_bgp_global

##### ANSIBLE VERSION

```paste below
any
```

##### COLLECTION VERSION

```paste below
arista.eos_bgp_global 4.1.1
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Configure BGP Global
  hosts: routers
  gather_facts: false
  vars:
    cfg:
      as_number: 65001
      router_id: 192.0.2.18
      neighbors:
      - neighbor_address: 198.51.100.1
        remote_as: 65002

  tasks:
    - name: Use BGP Global resource module [Cisco NX-OS]
      cisco.nxos.nxos_bgp_global:
        state: purged
        config: "{{ cfg }}"
      when: ansible_network_os == 'nxos'

    - name: Use BGP Global resource module [Arista EOS]
      arista.eos.eos_bgp_global:
        state: merged
        config: "{{ cfg }}"
      when: ansible_network_os == 'eos'
```

##### EXPECTED RESULTS

I expect the above playbook to work without any changes.

```yaml
cfg:
  as_number: 65001
  router_id: 192.0.2.18
  neighbors:
  - neighbor_address: 198.51.100.1
    remote_as: 65002 
```

##### ACTUAL RESULTS

```json
TASK [Use BGP Global resource module [Arista EOS]] ******************************************************************************************
[WARNING]: The value 65001 (type int) in a string field was converted to '65001' (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
[DEPRECATION WARNING]: Distribution fedora 35 on host clab-netgo-ceos should use /usr/bin/python3, but is using /usr/bin/python for backward
 compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See
 https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [clab-netgo-ceos]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false
}

MSG:

Unsupported parameters for (arista.eos.eos_bgp_global) module: neighbor_address found in config -> neighbor. Supported parameters include: additional_paths, allowas_in, auto_local_addr, default_originate, description, dont_capability_negotiate, ebgp_multihop, encryption_password, enforce_first_as, export_localpref, fall_over, graceful_restart, graceful_restart_helper, idle_restart_timer, import_localpref, link_bandwidth, local_as, local_v6_addr, maximum_accepted_routes, maximum_received_routes, metric_out, monitoring, next_hop_self, next_hop_unchanged, next_hop_v6_address, out_delay, peer, peer_group, prefix_list, remote_as, remove_private_as, route_map, route_reflector_client, route_to_peer, send_community, shutdown, soft_recognition, timers, transport, ttl, update_source, weight
```

```paste below

```
