### ISSUE TITLE
Formatting in `protocol_options` causes errors in rendering config.

### ISSUE THREAD

**Issue by josh-silvas** [ansible-collections/arista.eos#329]
##### SUMMARY

When using the `protocol_options` within the `arista.eos.eos_acls` module, the key of the option is used as the command line parameter ([appears here](https://github.com/ansible-collections/arista.eos/blob/main/plugins/module_utils/network/eos/config/acls/acls.py#L523-L539)), however, they are not a one-for-one match. I've included an example when using the echo_reply option.  It passes in the command `permit icmp any any echo_reply` which is invalid. The actual command contains echo-reply with a hyphen rather than an underscore (`permit icmp any any echo-reply`).

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.17
  config file = /Users/josh.silvas/ansible.cfg
  configured module search path = ['/Users/josh.silvas/modules']
  ansible python module location = /Users/josh.silvas/Library/Caches/pypoetry/virtualenvs/neteng-ansible-IOKhcaHE-py3.9/lib/python3.9/site-packages/ansible
  executable location = /Users/josh.silvas/Library/Caches/pypoetry/virtualenvs/neteng-ansible-IOKhcaHE-py3.9/bin/ansible
  python version = 3.9.5 (default, Jan 26 2022, 21:00:50) [Clang 13.0.0 (clang-1300.0.29.30)]
```

##### COLLECTION VERSION

```paste below
# /Users/josh.silvas/.ansible/collections/ansible_collections
Collection Version
---------- -------
arista.eos 4.1.1  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Arista DCS-7050SX3-48YC8-R
Hardware version:    11.15
Software image version: 4.22.3M

##### STEPS TO REPRODUCE

Attempting to apply a 

```yaml
---

- name: OBJECT-GROUP CONFIGURATION
  hosts: test_hosts
  connection: network_cli
  gather_facts: no
  tasks:
    - name: "REPLACE ACL CONFIGURATION"
      arista.eos.eos_acls:
        config:
        - afi: ipv4
          acls:
          - name: OUTSIDE
            aces:
            - sequence: 5
              remark: "--- ICMP ---"
            - sequence: 10
              source:
                any: true
              destination:
                any: true
              grant: permit
              protocol: icmp
              protocol_options:
                icmp:
                  echo_reply: true
        state: replaced
```

##### EXPECTED RESULTS

Access-list configuration to be applied to target device.

##### ACTUAL RESULTS

Command failed to apply due to invalid protocol_option type. `permit icmp any any echo_reply` vs. `permit icmp any any echo-reply`

```paste below
fatal: [test-device]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/josh.silvas/.ansible/tmp/ansible-local-81923q51x092e/ansible-tmp-1648071127.326127-81930-131353276683038/AnsiballZ_eos_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/josh.silvas/.ansible/tmp/ansible-local-81923q51x092e/ansible-tmp-1648071127.326127-81930-131353276683038/AnsiballZ_eos_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/josh.silvas/.ansible/tmp/ansible-local-81923q51x092e/ansible-tmp-1648071127.326127-81930-131353276683038/AnsiballZ_eos_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Users/josh.silvas/.pyenv/versions/3.9.5/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Users/josh.silvas/.pyenv/versions/3.9.5/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Users/josh.silvas/.pyenv/versions/3.9.5/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/9f/4hwqfyxn24929tycdf5mcyp40000gq/T/ansible_arista.eos.eos_acls_payload_879gx3p_/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py\", line 902, in <module>\n  File \"/var/folders/9f/4hwqfyxn24929tycdf5mcyp40000gq/T/ansible_arista.eos.eos_acls_payload_879gx3p_/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py\", line 897, in main\n  File \"/var/folders/9f/4hwqfyxn24929tycdf5mcyp40000gq/T/ansible_arista.eos.eos_acls_payload_879gx3p_/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py\", line 82, in execute_module\n  File \"/var/folders/9f/4hwqfyxn24929tycdf5mcyp40000gq/T/ansible_arista.eos.eos_acls_payload_879gx3p_/ansible_arista.eos.eos_acls_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: 10 permit icmp any any echo_reply\r\n% Invalid input\r\ntest-device(config-s-ansibl-acl-OUTSIDE)#\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
