### ISSUE TITLE
ACL updates not treated as 'changes'

### ISSUE THREAD

**Issue by mostdaysarebaddays** [ansible-collections/arista.eos#349]
##### SUMMARY
ACL updates not treated as 'changes'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
```

##### COLLECTION VERSION

```paste below
arista.eos:5.0.0
```

##### CONFIGURATION

```paste below
Empty 
```

##### OS / ENVIRONMENT

Centos7

##### STEPS TO REPRODUCE

Any ACL config changes aren't treated as changes as below.

```yaml

    - name: get content of local file - to add config
      set_fact:
        commandstoruntoadd: "{{ lookup('file','CFGS/' + ansible_host + '.txt') }}"
      tags:
       - add

    - name: "Apply config"
      eos_config:
        lines:
           - " {{commandstoruntoadd}} "
      register: configappliedtoadd
      tags:
        - add

Content of .txt file

interface Ethernet1
spanning-tree vlan 1-4094 cost 99999999
router bgp 666
neighbor 1.1.1.1 description test
ip access-list extended test
permit ip 6.6.6.64/31 any
permit ip 6.6.6.66/31 any

```

##### EXPECTED RESULTS

I expect exactly as below but the:

    - Ip access-list extended test
    - Permit ip 6.6.6.64/31 any
    - Permit ip 6.6.6.66/31 any
    
  Should be under diff with + next to them

##### ACTUAL RESULTS

All other config treated as 'changes', ACL updates are not.

```paste below
TASK [Apply config output] *******************************************************************************************************************************************************************************************************************
ok: [test-box] =>
  msg:
    ansible_facts:
      discovered_interpreter_python: /usr/bin/python
    changed: true
    commands:
    - Interface Ethernet1
    - Spanning-tree vlan 1-4094 cost 99999999
    - Router bgp 666
    - Neighbor 1.1.1.1 description test
    - Ip access-list extended test
    - Permit ip 6.6.6.64/31 any
    - Permit ip 6.6.6.66/31 any
    diff:
      prepared: |-
        --- system:/running-config
        +++ session:/ansible_1651029109-session-config
        @@ -75,6 +75,7 @@
            switchport mode trunk
            ptp enable
        +   spanning-tree vlan 1-4094 cost 99999999
         !
         interface Ethernet2
            description ***
        @@ -305,6 +306,8 @@
            neighbor INTERNAL timers 3 9
            neighbor INTERNAL send-community
            neighbor INTERNAL maximum-routes 12000
        +   neighbor 1.1.1.1 description test
        +   neighbor 1.1.1.1 maximum-routes 12000
            neighbor 10.255.255.2 remote-as 666
            neighbor 10.255.255.2 route-map BGP_advertise out
            neighbor 10.255.255.2 maximum-routes 12000
    failed: false
    session: ansible_1651029109
    updates:
    - Interface Ethernet1
    - Spanning-tree vlan 1-4094 cost 99999999
    - Router bgp 666
    - Neighbor 1.1.1.1 description test
    - Ip access-list extended test
    - Permit ip 6.6.6.64/31 any
    - Permit ip 6.6.6.66/31 any

```
