### ISSUE TITLE
port security module

### ISSUE THREAD

**Issue by nickper** [ansible-collections/arista.eos#359]
##### SUMMARY
An module to manage port security settings like bpduguard, storm-control etc. on an interface

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
eos_portsecurity_interfaces

##### ADDITIONAL INFORMATION
Currently it is only possible to manage port security configuration via the eos_commands module. But it would be nice to have it via an dedicated module.

```yaml
  - name: get interfaces
    arista.eos.eos_portsecurity_interfaces:
      state: gathered
    register: all_interfaces

  - name: set bpduguard
    loop: "{{ interfaces }}"
    arista.eos.eos_l2_interfaces:
      config:
        - name: "{{ item }}"
          spanning-tree: 
            bpduguard: True
            portfast: True
```
