### ISSUE TITLE
Introduce output json to eos_config

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#373]
##### SUMMARY
It would be useful to natively use ansible when backing up or applying config, for the `show running-config` via the json format.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
eos_config

##### ADDITIONAL INFORMATION

```yaml
- name: backup config in json format
  arista.eos.eos_config:
    backup: yes
    output: json
    backup_options:
      filename: backup.json
      dir_path: /home/user
```
