### ISSUE TITLE
Allow override of supports_onbox_diff 

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#374]
##### SUMMARY
It would be useful to natively use ansible when backing up or applying config, if `diff` option is selected, to override the `supports_onbox_diff` even when the remote eos device supports diff on box.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
eos_config

##### ADDITIONAL INFORMATION

```yaml
- name: diff full configs off box
  arista.eos.eos_config:
    src: {{ inventory_hostname }}.cfg
    replace: config
    diff_onbox: False
  check_mode: True
  diff: True
  register: audit_config
```
