### ISSUE TITLE
Commit timer support

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#375]
There are instances where it is useful to be able to do a `commit timer`, have the configuration changes take effect, and if you make a mistake and knock something offline, the changes get automatically reverted.

Arista EOS has support for sessions and a `commit timer` syntax.

We tried disabling the automatic sessions that Ansible creates via the `export ANSIBLE_EOS_USE_SESSIONS=False` so that we had more granular control of the sessions.

The problem is that at the end of the module call, the `commit timer` switches the CLI out of `config` mode, but the `eos` ansible code [sends a "end" command](https://github.com/ansible-collections/arista.eos/blob/3a65a7b8a6601305cea86969777bce076c284c0e/plugins/cliconf/eos.py#L179) which causes an error.

For example:

```yaml
- set_fact: configfile="{{ config_dir }}/templ.cfg"
  tags: push_config

- name: Push config to {{inventory_hostname}}
  eos_config:
    src: "{{configfile}}"
    backup: yes
    backup_options:
      dir_path: "{{backout_dir}}"
      filename: "{{inventory_hostname}}"
    diff_against: running
  register: push_config
  tags: push_config
```

templ.cfg
```
configure session CM99999
no ip access-list testacl
ip access-list testacl
   88 permit ip any any

commit timer 00:05:00
```

```
TASK [Push config to test] ******************************************************************************
fatal: [test]: FAILED! => {"changed": false, "data": "end\r\n% Invalid input\r\nVM1test#", "msg": "end\r\n% Invalid input\r\nVM1test.#"}
```

We have versions of this where `ignore_errors: True` for the `eos_config` task is used, but it seems hacky. I would prefer that we either expose the ability to do a commit and confirm, similar to how Juniper has the [confirm_commit](https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_config_module.html#parameter-confirm_commit) argument available, or at least have some logic where we don't send the `end` command if there was a `commit timer` sent.
