### ISSUE TITLE
After adding config lock to Arista switch I cannot do diff against session

### ISSUE THREAD

**Issue by Rohit-Salunke** [ansible-collections/arista.eos#409]
##### SUMMARY
I want to do get config diff before applying my config changes. There are daemon on switch that are running after an interval they might update config. When I want to apply my changes I want to make sure other (daemon) changes are not applied when I am pushing my config changes.

To handle this scenario I have tried adding config lock first, after this when I am doing diff against session ansible expects me to remove the lock as I am using eos_config module to do diff against session.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml
- name: Get configuration lock
    eos_command:
      commands:
        - configure lock transaction {{ transaction_name }} {{ reason }}
      provider: "{{ credentials }}"
    register: update_lock
    retries: 12
    delay: 5
    until: "'stdout' in update_lock.keys()"
- name: Diff the running config against generated config
     eos_config:
        provider: "{{ credentials }}"
        diff_against: session
        src: "my_changes.conf"
        replace: config
      register: config_diff_resp
      check_mode: true
      diff: true
```
Error log:
`TASK [network_scripts : Diff the running config against generated config] ******************************************************************************************************
fatal: [padpla201]: FAILED! => {"changed": false, "code": 1006, "msg": "Unable to run this command (configuration is locked by another session)"}
`
