### ISSUE TITLE
Wrong command when setting source interface in server config

### ISSUE THREAD

**Issue by marcinszukala** [ansible-collections/arista.eos#423]
##### SUMMARY
When configuring source interface in server config, generated command that is send to switch has "local_interface" instead of "local-interface". It is not a valid command in EOS, resulting in error

I was able to fix by changing line 77 in /usr/share/ansible/collections/ansible_collections/arista/eos/plugins/module_utils/network/eos/rm_templates/ntp_global.py

        command += " local-interface {local_interface}".format(**el)
        #command += " local_interface {local_interface}".format(**el)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_ntp_global

##### ANSIBLE VERSION
```
ansible [core 2.11.12]
  python version = 3.6.8
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION
```
Collection Version
---------- -------
arista.eos 6.0.1  

```

##### STEPS TO REPRODUCE
Try do configure source interface on ntp server level

```
  tasks:

    - name: ntp config
      arista.eos.eos_ntp_global:
        config:
          servers:
            - server: "1.1.1.1"
              local_interface: "Management 1"

```

##### EXPECTED RESULTS
Command send to the switch should be like:

```
ntp server 1.1.1.1 local-interface Management 1
```

##### ACTUAL RESULTS
Command that was sent to switch was:

```
ntp server 1.1.1.1 local_interface Management 1

```
