### ISSUE TITLE
ansible.eos.eos_config "defaults: True" option takes a very long time

### ISSUE THREAD

**Issue by michaeljaboyd** [ansible-collections/arista.eos#441]
##### SUMMARY
The follow code takes up to 6 minutes to run. whereas running the commands manually "term len 0" followed by "show run all" completes in seconds. 
```
- name: take backup of config
      arista.eos.eos_config:
        defaults: True
        backup: True
        backup_options:
          dir_path: "/tmp/"
      register: running_config_backup
      vars:
        ansible_command_timeout: 600
```

##### ISSUE TYPE
Slow command output. This makes the playbook very slow

##### COMPONENT NAME
arista.eos.eos_config

##### ANSIBLE VERSION
```
ansible [core 2.13.10]
  config file = /home/user/git/network/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/git/network/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = ./bin/ansible
  python version = 3.8.13 (default, Aug 16 2022, 12:16:29) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
  
```

##### COLLECTION VERSION
```
N/A installed from pip
```

##### CONFIGURATION

``` python3.8
```

##### OS / ENVIRONMENT
Centos 7
7260cx3

##### STEPS TO REPRODUCE
in hosts file
```
[all:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
ansible_network_os=arista.eos.eos
```
in playbook
```- name: take backup of config
      arista.eos.eos_config:
        defaults: True
        backup: True
        backup_options:
          dir_path: "/tmp/"
      register: running_config_backup
      vars:
        ansible_command_timeout: 600```

##### EXPECTED RESULTS
the command to complete in a similar time to the command line interface


##### ACTUAL RESULTS
It takes 6 minutes for the module to complete. 2 minutes on a 7280TR
