### ISSUE TITLE
[acls] example does not work

### ISSUE THREAD

**Issue by NilashishC** [ansible-collections/arista.eos#459]
##### SUMMARY
- Example ACL tasks do not work.
- Currently blocks ACLs documentation improvement work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_acls.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.4]
  config file = /home/nchakrab/ansible-collections/ansible.cfg
  configured module search path = ['/home/nchakrab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nchakrab/.virtualenvs/core/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nchakrab/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/nchakrab/.virtualenvs/core/bin/ansible
  python version = 3.10.8 (main, Nov  4 2022, 12:40:05) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/home/nchakrab/.virtualenvs/core/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
latest
```

##### OS / ENVIRONMENT

```
vEOS#show version
 vEOS
Hardware version:      
Serial number:         
Hardware MAC address:  5254.00a5.854d
System MAC address:    5254.00a5.854d

Software image version: 4.24.6M
Architecture:           i686
Internal build version: 4.24.6M-22486697.4246M
Internal build ID:      2f026fab-f3ea-4171-9e76-42c5c3dedf3e

Uptime:                 0 weeks, 0 days, 0 hours and 26 minutes
Total memory:           6057632 kB
Free memory:            5189240 kB

```

##### STEPS TO REPRODUCE

The ACL lines in the configure task are from the documentation examples.

```yaml
---
- name: ACLs
  hosts: eos
  gather_facts: false
  tasks:
    - arista.eos.eos_acls:
        state: deleted
      tags: setup

    - arista.eos.eos_config:
        match: none
        lines:
          - ip access-list test1
          - 10 permit ip 10.10.10.0/24 any ttl eq 200
          - 20 permit ip 10.30.10.0/24 host 10.20.10.1
          - 30 deny tcp host 10.10.20.1 eq finger www any syn log
          - 40 permit ip any any
          - ipv6 access-list test2
          - 10 deny icmpv6 any any reject-route hop-limit eq 20
      tags: setup

    - name: Merge provided configuration with device configuration
      arista.eos.eos_acls:
        state: gathered
```

##### EXPECTED RESULTS
Facts gathered without error.

##### ACTUAL RESULTS

```paste below
fatal: [veos]: FAILED! => changed=false 
<...redacted for brevity...>
  msg: 'Unsupported parameters for (basic.py) module: config.line. Supported parameters include: acls, afi.'
```
