### ISSUE TITLE
arista.eos.eos_acls `log: false` treated as `log: true`

### ISSUE THREAD

**Issue by bewing** [ansible-collections/arista.eos#470]
##### SUMMARY
Placing `log: false` in an ACE results in the `log` statement being present in the config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
arista.eos.eos_acls

##### ANSIBLE VERSION
```shell
$ ansible --version
ansible [core 2.15.5]
  config file = /home/bewing/.ansible.cfg
  configured module search path = ['/home/bewing/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /export/home/bewing/.pyenv/versions/3.9.18/lib/python3.9/site-packages/ansible
  ansible collection location = /export/home/bewing/.ansible/collections:/usr/share/ansible/collections
  executable location = /export/home/bewing/.pyenv/versions/3.9.18/bin/ansible
  python version = 3.9.18 (main, Oct 19 2023, 17:02:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/home/bewing/.pyenv/versions/3.9.18/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```shell
$ ansible-galaxy collection list arista.eos

# /export/home/bewing/.ansible/collections/ansible_collections
Collection Version
---------- -------
arista.eos 6.1.2
```

##### CONFIGURATION
```shell
$ ansible-config dump --only-changed

```

##### STEPS TO REPRODUCE

```yaml
---
- name: example acl
  arista.eos.eos_acls:
    config:
    - afi: ipv4
      acls:
      - name: test-acls
        aces:
        - sequence: 10
          grant: allow
          destination:
            any: true
          source:
            any: true
          protocol: ip
          log: false
```

##### EXPECTED RESULTS
```
ip access-list test-acls
  seq 10 permit ip any any
```

##### ACTUAL RESULTS
```
ip access-list test-acls
  seq 10 permit ip any any log
```

root cause:  https://github.com/ansible-collections/arista.eos/blob/eb7f54865bb3c0f0e66c97f1ef6e0eeacb8c7360/plugins/module_utils/network/eos/config/acls/acls.py#L585-L586

suggest changing to

```python
if ace.get("log", False):
    command = command + " log"
```
