### ISSUE TITLE
Deleteting `remarks` ACEs in ACL will destroy whole ACL

### ISSUE THREAD

**Issue by TheRealBecks** [ansible-collections/arista.eos#498]
##### SUMMARY
When deleting a `port_protocol` from an ACL ACE the `no <sequence number>` command is missing and an error-message will be provided as the to be changed/configured sequence number already exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`eos_acls`

##### ANSIBLE VERSION

```
ansible [core 2.15.6]
  config file = /home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg
  configured module search path = ['/home/mbeckert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mbeckert/.local/share/virtualenvs/lightning-vg2lOQBb/lib/python3.11/site-packages/ansible
  ansible collection location = /home/mbeckert/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mbeckert/.local/share/virtualenvs/lightning-vg2lOQBb/bin/ansible
  python version = 3.11.6 (main, Nov 15 2023, 09:22:27) [GCC] (/home/mbeckert/.local/share/virtualenvs/lightning-vg2lOQBb/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection        Version
----------------- -------
community.general 7.5.1
```

##### CONFIGURATION

```
CONFIG_FILE() = /home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg
DEFAULT_FORKS(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = 10
DEFAULT_HASH_BEHAVIOUR(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = ['/home/mbeckert/Entwicklung/Strato/lightning/lightning/inventory.yml']
DEFAULT_ROLES_PATH(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = ['/home/mbeckert/Entwicklung/Strato/lightning/lightning/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = /home/mbeckert/Entwicklung/Strato/lightning/lightning/.vault_passphrase/open_vault.sh
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Arista EOS 4.28.4M

##### STEPS TO REPRODUCE

Before `task.yml`:
```yaml
---
- name: Remark test
  arista.eos.eos_acls:
    state: "replaced"
    config:
      - afi: ipv4
        acls:
          - name: test-acl3
            aces:
              - sequence: 10
                remark: test foo
              - sequence: 20
                grant: permit
                protocol: udp
                source:
                  any: true
                destination:
                  any: true

```

After `task.yml`:
```yaml
---
- name: Remark test
  arista.eos.eos_acls:
    state: "replaced"
    config:
      - afi: ipv4
        acls:
          - name: test-acl3
            aces:
              # - sequence: 10
              #   remark: test foo
              - sequence: 10
                grant: permit
                protocol: udp
                source:
                  any: true
                destination:
                  any: true

```
-> Sequence 10 will be deleted and 20 will be the new 10

##### EXPECTED RESULTS

On the second run the sequence number 10 will be deleted before a new 10 will be configured.

To be generated `commands`:
```
[
  'ip access-list test-acl2',
  'no 10',
  'no 20',
  '10 permit udp any any'
]
```

##### ACTUAL RESULTS

On the second run on the configuration will fail on the device:

Generated `commands`:
```
[
  'ip access-list test-acl3',
  'no 10',
  'no 20',
  '10 remark test foo permit udp any any'
]
```

##### ROOT CAUSE
`get_updated_ace(w, h)` will be called:
https://github.com/ansible-collections/arista.eos/blob/2342353ac094f3354c59682dd3d976e66d13a0fe/plugins/module_utils/network/eos/config/acls/acls.py#L456-L466

In this example the content of the variables are:
`w`:
```
{
    'destination': {
        'any': True
    },
    'grant': 'permit',
    'protocol': 'udp',
    'sequence': 10,
    'source': {
        'any': True
    }
}
```

`h`:
```
{
    'remark': 'test foo',
    'sequence': 10
}
```

`w_updated` (return value):
```
{
    'destination': {
        'any': True
    },
    'grant': 'permit',
    'protocol': 'udp',
    'remark': 'test foo',
    'sequence': 10,
    'source': {
        'any': True
    }
}
```
-> Both ACEs have been merged, but **WHY**? Merging and also overriding ACEs is **not** possible at all. An existing ACE needs to be deleted with a `no <sequence number>` first before a new one gets added.

The only call of `get_updated_ace(w, h)` happens here:
https://github.com/ansible-collections/arista.eos/blob/2342353ac094f3354c59682dd3d976e66d13a0fe/plugins/module_utils/network/eos/config/acls/acls.py#L441-L450

My suggestion:
```python
if wace["sequence"] == hace["sequence"]:
   if wace == hace:
       want_aces.pop(want_aces.index(wace))
```
And also the deletion of `get_updated_ace(w, h)`
