### ISSUE TITLE
eos_l2_interfaces mode not found

### ISSUE THREAD

**Issue by dragosstan2602** [ansible-collections/arista.eos#51]
##### SUMMARY
When I run this task:
```
    - name: Merge provided configuration with device configuration. # Only with network_cli
      eos_l2_interfaces:
        config:
          - name: Ethernet41
            mode: trunk
            trunk:
              native_vlan: 666
              trunk_allowed_vlans: 15, 16, 20
        state: merged
```
I get this error:
```
"msg": "Unsupported parameters for (eos_l2_interfaces) module: mode found in config. Supported parameters include: access, name, trunk"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
arista.eos.eos_l2_interfaces

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /Users/dstan/PycharmProjects/CODE/ansible_lab/ansible.cfg
  configured module search path = ['/Users/dstan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dstan/PycharmProjects/VENV/ansible_lab/lib/python3.7/site-packages/ansible
  executable location = /Users/dstan/PycharmProjects/VENV/ansible_lab/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]

```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
DEFAULT_GATHERING(/Users/dstan/PycharmProjects/CODE/ansible_lab/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/Users/dstan/PycharmProjects/CODE/ansible_lab/ansible.cfg) = ['/Users/dstan/PycharmProjects/CODE/ansible_lab/inv.yaml']
PARAMIKO_HOST_KEY_AUTO_ADD(/Users/dstan/PycharmProjects/CODE/ansible_lab/ansible.cfg) = True
RETRY_FILES_ENABLED(/Users/dstan/PycharmProjects/CODE/ansible_lab/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
Arista DCS-7280SR-48C6-R
Hardware version:    11.03
Serial number:       XYZ
System MAC address:  0000.1111.2222

Software image version: 4.18.1F
Architecture:           i386
Internal build version: 4.18.1F-4591672.4181F
Internal build ID:      63d2e89a-220d-4b8a-a9b3-0524fa8f9c5f
```

##### STEPS TO REPRODUCE
Described in SUMMARY

##### EXPECTED RESULTS
```
interface Ethernet41
   switchport trunk native vlan 666
   switchport trunk allowed vlan 15-16,20
   switchport mode trunk
```

##### ACTUAL RESULTS
```
interface Ethernet41
   switchport trunk native vlan 666
   switchport trunk allowed vlan 15-16,20
```
```
"msg": "Unsupported parameters for (eos_l2_interfaces) module: mode found in config. Supported parameters include: access, name, trunk"
```

**Comment by dragosstan2602** [comment]
I understand this has been addressed in an already closed issue but it still doesn't work. The docs mention it but the error still pops up.

**Comment by dragosstan2602** [comment]
Hi @GomathiselviS, I tried using `arista.eos.eos_l2_interfaces` but that doesn't seem to work either. Same issue:
```
fatal: [lab-sw304a]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "mode": "trunk",
                    "name": "Ethernet41",
                    "trunk": {
                        "native_vlan": 666,
                        "trunk_allowed_vlans": 666
                    }
                }
            ],
            "state": "merged"
        }
    },
    "msg": "Unsupported parameters for (arista.eos.eos_l2_interfaces) module: mode found in config. Supported parameters include: access, name, trunk"
}
```
Here's my playbook just in case (nothing changed in the info i provided initially):
```
    - name: Merge provided configuration with device configuration.
      arista.eos.eos_l2_interfaces:
        config:
          - name: Ethernet41
            mode: trunk
            trunk:
              native_vlan: 666
              trunk_allowed_vlans: 666
        state: merged
```
There's a possibility that I'm doing something wrong of course but I followed your docs and this is what I got. If you need more info from me I'll happily provide it. Thanks!
