### ISSUE TITLE
eos_bgp_global cannot specify "in" and "out" route-maps for neighbor

### ISSUE THREAD

**Issue by yheffen** [ansible-collections/arista.eos#538]
##### SUMMARY
It is not unusual to specify both incoming and outgoing route-maps to a BGP neighbor,

router bgp 65000
   local-as 65000
   router-id 192.0.2.1
   neighbor 192.0.2.2 route-map MAP_INCOMING in
   neighbor 192.0.2.2 route-map MAP_OUTGOING out

In the YAML for eos_bgp_global, there is only a single "route_map" dict per neighbor. It means you can have one or the other, but not both.

The cisco.ios.ios_bgp_global module handles this by instead having "route_maps" which is a list of dicts. Looks like they had "route_map" too, but have deprecated it.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by roverflow** [comment]
@yheffen Can you add a playbook as an example for the above

**Comment by yheffen** [comment]
```
---

- name: Show route_map problem
  hosts: router.example.com

  tasks:
  - name: BGP Global
    arista.eos.eos_bgp_global:
      state: merged
      config:
        as_number: "4220000000"
        neighbor:
        - neighbor_address: "192.0.2.1"
          route_map:
            name: "MAP_INCOMING"
            direction: "in"
          route_map:
            name: "MAP_OUTGOING"
            direction: "out"

```
Adding a neighbor to an existing BGP configuration.

Output from the playbook run (notice the immediate warning),

```
$ ansible-playbook eos_bgp_global-route_map.yml 
[WARNING]: While constructing a mapping from /home/criclar/ansible/playbooks/eos_bgp_global-route_map.yml, line 13, column 11, found a duplicate dict key (route_map). Using last
defined value only.

PLAY [Show route_map problem] ***********************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
Monday 13 May 2024  16:58:08 -0700 (0:00:00.028)       0:00:00.028 ************ 
ok: [router.example.com]

TASK [BGP Global] ***********************************************************************************************************************************************************************
Monday 13 May 2024  16:58:12 -0700 (0:00:03.715)       0:00:03.744 ************ 
changed: [router.example.com]

PLAY RECAP ******************************************************************************************************************************************************************************
router.example.com    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Monday 13 May 2024  16:58:17 -0700 (0:00:04.653)       0:00:08.397 ************ 
=============================================================================== 
BGP Global ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.65s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 3.72s

```
Actual neighbor info added to router,

```
router#sh run | i neighbor 192.0.2.1
   neighbor 192.0.2.1 route-map MAP_OUTGOING out
router#
```
