### ISSUE TITLE
Disabling NTP authentication does not work

### ISSUE THREAD

**Issue by oghoneim** [ansible-collections/arista.eos#549]
##### SUMMARY
When trying to configure  ntp on a switch running EOS 4.31.3M the ntp ansible module will not disable authentication

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

arista.eos.eos_ntp_global module

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/miro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/miro/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/miro/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/miro/.local/bin/ansible
  python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = False

```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
arista.eos 10.0.0 

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols
DUPLICATE_YAML_DICT_KEY(/etc/ansible/ansible.cfg) = error
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

EOS 4.31.3M

##### STEPS TO REPRODUCE

I'm trying to run the following task:

```yaml
- name: Setup NTP
  arista.eos.eos_ntp_global:
    config:
      authenticate:
        enable: false
        servers: false
      local_interface: "Management1"
      servers:
        - server: "0.pool.ntp.org"
        - server: "1.pool.ntp.org"
```

##### EXPECTED RESULTS

I expect the switch config to be:
```
ntp local-interface Management1
ntp server 0.pool.ntp.org
ntp server 1.pool.ntp.org
```

##### ACTUAL RESULTS

However the command 'ntp authenticate' is still on the switch causing ntp sync to fail

```paste below
ntp authenticate
ntp local-interface Management1
ntp server 0.pool.ntp.org
ntp server 1.pool.ntp.org
```
