### ISSUE TITLE
eos_interfaces.config.speed not being parsed correctly for breakout ports

### ISSUE THREAD

**Issue by diego-lopez8** [ansible-collections/arista.eos#551]
##### SUMMARY

eos_interfaces.config.speed and eos_interfaces.config.duplex are not parsing correctly when using a breakout configuration on a interface. When trying to gather interface information from a device, the speed and duplex is not parsed correctly, and the module is unable to apply a breakout via the `speed` command which is possible on the device itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

eos_interfaces.config.speed and eos_interfaces.config.duplex

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.12]
  config file = /Users/diego/.ansible.cfg
  configured module search path = ['/Users/diego/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/diego/miniforge3/envs/net/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/diego/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/diego/miniforge3/envs/net/bin/ansible
  python version = 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08) [Clang 15.0.7 ] (/Users/diego/miniforge3/envs/net/bin/python3.9)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/diego/.ansible/collections/ansible_collections
Collection Version
---------- -------
arista.eos 10.0.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/diego/.ansible.cfg
DEFAULT_TIMEOUT(/Users/diego/.ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Arista DCS-7050DX4-32S-F
Software image version: 4.32.1F

##### STEPS TO REPRODUCE

Run a play with "Gather" state to fetch configuration of an interface which has a breakout already applied via `speed 100g-2`:

Switch has the following configuration
```
interface Ethernet1/1
   description Just a Breakout Interface
   mtu 9100
   speed 100g-2
   channel-group 1 mode active
!
interface Ethernet1/3
!
interface Ethernet1/4
!
interface Ethernet1/5
!
interface Ethernet1/6
!
interface Ethernet1/7
!
interface Ethernet1/8
!
```
Run the following play
```yaml
- name: Configure interfaces on Arista switches
  hosts: all
  gather_facts: true
  connection: network_cli
  tasks:
  - name: Gather interfaces facts from the device
    arista.eos.interfaces:
      state: gathered
    register: if
  - name: debugging
    debug:
      var: if
```
##### EXPECTED RESULTS
I expect 
```
            {
                "description": "Just a Breakout Interface",
                "enabled": true,
                "mtu": 9100,
                "name": "Ethernet1/1",
                "speed": "100g-2"
            },
```
##### ACTUAL RESULTS
The actual results of the gather play is 
```
            {
                "description": "Just a Breakout Interface",
                "duplex": "0g-2",
                "enabled": true,
                "mtu": 9100,
                "name": "Ethernet1/1",
                "speed": "10"
            },
            {
                "enabled": true,
                "name": "Ethernet1/3"
            },
            {
                "enabled": true,
                "name": "Ethernet1/4"
            },
            {
                "enabled": true,
                "name": "Ethernet1/5"
            },
            {
                "enabled": true,
                "name": "Ethernet1/6"
            },
            {
                "enabled": true,
                "name": "Ethernet1/7"
            },
            {
                "enabled": true,
                "name": "Ethernet1/8"
            },
```
The parser believes that the speed is `10` and the duplex is `0g-2`. 

Output of `show interfaces ethernet 1/1 hardware`:
```
Ethernet1/1
  Model: DCS-7050DX4-32S
  Type: 400GBASE-DR4
  Speed/duplex: 100G-2/full,400G-8/full(default)
  Flowcontrol: rx-(off,on),tx-(off,on)
  Error correction: reed-solomon(100G-2(default),400G-8(default)), fire-code(none), disabled(none)
```
Another example for `state: merged`:

Run the play:
```
- name: Configure interfaces on Arista switches
  hosts: all
  gather_facts: true
  connection: network_cli
  tasks:
  - name: Gather interfaces facts from the device
    arista.eos.interfaces:
      config:
        - name: Ethernet5/1
          speed: 100g-2
      state: merged
```

##### EXPECTED RESULTS
I expect the `speed 100g-2` to be applied to the switch, and for the breakout to be created.

##### ACTUAL RESULTS
Results of the play:
```
fatal: [hsrn-sw22a-1mt]: FAILED! => {
    "changed": false,
    "module_stderr": "speed 100g-2None\r\n% Invalid input\r\nHSRN-SW22A-1MT(config-s-ansible_17-if-Et5/1)#",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```
