### ISSUE TITLE
eos_l2_interfaces does not clear out switchport trunk mode

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#60]
##### SUMMARY

The `eos_l2_interfaces` module does not clear out `switchport mode trunk`
when an interface, with a previous configuration, is converted from a trunk port to an access port

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.2
  python version = 3.8.1 (default, Dec 27 2019, 18:05:45) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### STEPS TO REPRODUCE
```
Last login: Thu Jun 18 16:30:45 2020 from 10.30.117.246
tor01>enable
tor01#config
tor01(config)#default interface ethernet37
tor01(config)#interface ethernet37
tor01.(config-if-Et37)#switchport mode trunk
tor01.(config-if-Et37)#show ac
interface Ethernet37
   switchport mode trunk
```

```yaml

    - name: Configure L2 ports
      eos_l2_interfaces:
        config:
          - name: Ethernet37
            access:
              vlan: 699
        state: replaced
```

##### EXPECTED RESULTS

```
tor01(config-if-Et37)#show ac
interface Ethernet37
   switchport access vlan 699
```
##### ACTUAL RESULTS

```
tor01(config-if-Et37)#show ac
interface Ethernet37
   switchport access vlan 699
   switchport mode trunk
```
