### ISSUE TITLE
eos_lag_interfaces name parameter requires 'Port-Channel' in the name despite documentation stating otherwise

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#79]
The documentation for `eos_lag_interfaces` has examples such as

```
- name: Override all device configuration of all LAG attributes with provided configuration
  eos_lag_interfaces:
    config:
      - name: 10
        members:
          - member: Ethernet2
            mode: on
    state: overridden

```

However, the code that actually appears to implement this, uses the 12th letter of the `name` parameter, forward. 

https://github.com/ansible-collections/arista.eos/blob/9c38a1590ea031a6dbf3e4a93e40d0f04f319b57/plugins/module_utils/network/eos/config/lag_interfaces/lag_interfaces.py#L244

So following the documentation, you end up with an error because if you create a name of just `10` like the documentation states, `channel_id` turns into an empty string, which yields flawed commands and results in an error

```
ansible.module_utils.connection.ConnectionError: channel-group  mode on% Invalid input
```

Manaully fixing this by doing 

```
- name: Override all device configuration of all LAG attributes with provided configuration
  eos_lag_interfaces:
    config:
      - name: Port-Channel10
        members:
          - member: Ethernet2
            mode: on
    state: overridden
```

Corrects this issue.
