### ISSUE TITLE
How to override httpapi plugin?

### ISSUE THREAD

**Issue by garbled1** [ansible-collections/arista.eos#82]
##### SUMMARY

Even though I am using the collection, and specify it in both collections requirements, and inside my play, ansible still uses the built-in httpapi plugin, which is older, and not as functional as the one you ship.  How do I force it to use the one shipped with the collection?

This example is from AWX, but I see the exact same issue on the commandline.  For now I've just hacked around it by replacing the ansible one with the one prodvided here, but...

<hostnameXXX> loaded API plugin eos from path /opt/awx_venvs/eos_py27/lib/python2.7/site-packages/ansible/plugins/httpapi/eos.py for network_os eos

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

httpapi/eos.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = None
  configured module search path = [u'/home/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/awx_venvs/eos_py27/local/lib/python2.7/site-packages/ansible
  executable location = /opt/awx_venvs/eos_py27/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
none
```

##### OS / ENVIRONMENT

Debian 10 controller

##### STEPS TO REPRODUCE

```yaml
---
- hosts: eos
  gather_facts: no
  collections:
  - arista.eos
  tasks:
    - name: Create a napalm user
      eos_user:
        name: napalm
        configured_password: '{{ napalm_password }}'
        update_password: on_create
        state: present

```

##### EXPECTED RESULTS

Expect it to find the one in the arista.eos collection and use that, not the one supplied by ansible.

##### ACTUAL RESULTS

```paste below
<hostnameXXX> loaded API plugin eos from path /opt/awx_venvs/eos_py27/lib/python2.7/site-packages/ansible/plugins/httpapi/eos.py for network_os eos
```
